name: ci

on:
  pull_request:
    branches:
      - master

jobs:
   CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Flutter install
        uses: subosito/flutter-action@v2
        with:
         flutter-version: '2.10.5'
         channel: 'stable'
      - run: flutter --version
      
      - name: Run Unit Tests
        run: flutter test
           
      - name: Quality Code
        run: flutter analyze
